# config.py

REMOTE_IP = "192.168.1.11"
LOSS_THRESHOLD_PERCENT = 10.0
LATENCY_THRESHOLD_MS = 70

START_STREAMS = 2
MAX_STREAMS = 16

BW_INCREMENT_SAFE = 10
BW_INCREMENT_MODERATE = 50
BW_INCREMENT_AGGRESSIVE = 100
NO_GAIN_STREAM_LIMIT = 2

PLATEAU_PERCENT = 0.05
MAX_WINDOW_SIZE = 5
MAX_STAGNATION_ITER = 6

THEME = "flatly"  # ttkbootstrap theme
FONT = ("Segoe UI", 10)
TITLE_FONT = ("Arial", 12, "bold")
